### ISSUE TITLE
Can't import bistro scene due to missing `Non-Color` color space

### ISSUE THREAD

**Issue by jakobhellermann** [aclysma/rendering-demo-scenes#1]
Following [bistro.md](https://github.com/aclysma/rendering-demo-scenes/blob/main/bistro/bistro.md) I get the following error in `import_fbx.load`:
```
TypeError: bpy_struct: item.attr = val: enum "Non-Color" not found in ('Linear', 'sRGB')
```
I'm using Blender 2.93.3.

Do you know what might be the problem here?

**Comment by jakobhellermann** [comment]
My blender UI only shows these two color spaces as well

![grafik](https://user-images.githubusercontent.com/22177966/147359197-14bd643b-9486-4bab-ae4d-a0016efd1131.png)

while other people seem to have more options.

![grafik](https://user-images.githubusercontent.com/22177966/147359218-b3d5846f-015d-4f71-ad75-be71eb9449ef.png)

**Comment by aclysma** [comment]
I'm on blender 2.93.5. Is it possible it's a limitation of exr textures?

**Comment by jakobhellermann** [comment]
I just imported a random sample exr texture to see the options.

**Comment by jakobhellermann** [comment]
I just reinstalled blender (3.0.0 now) and got further but it still crashed:
```
ERROR (bke.bpath): source/blender/blenkernel/intern/bpath.c:230 BKE_bpath_relative_convert: basedir='', this is a bug
Info: Saved "bistro.blend"
Info: Saved "bistro.blend"

Blender quit
```

I'll try again with a freshly installed 2.93.

**Comment by jakobhellermann** [comment]
Same error in 2.93, but the `bistro.blend` file is still generated so I suppose it's no problem.
